### PR TITLE
TSS-106 - Progress update for barrier details

### PR DESCRIPTION
**Pull request by jamespacileo**

### CODE REVIEW

**Comment by Santino-Trade** [comment]
The unit tests are failing

**Review by Santino-Trade — APPROVED** [review]

**Comment by Santino-Trade** [comment]
We need to hide the functionality behind the env file feature flag set up in resolution date search ticket MINISTERIAL_REPORTS_FUNCTIONALITY.
Check line 25 of templates/partials/forms/checkbox_filter.html where we can just avoid loading the new HTML elements. We'll need a ticket next sprint to clean up and remove it.

**Comment by jamespacileo** [comment]
> We need to hide the functionality behind the env file feature flag set up in resolution date search ticket MINISTERIAL_REPORTS_FUNCTIONALITY.
Check line 25 of templates/partials/forms/checkbox_filter.html where we can just avoid loading the new HTML elements. We'll need a ticket next sprint to clean up and remove it. 

added! Thanks for spotting this!

**Comment by jamespacileo** [comment]
> The unit tests are failing 

fixed

**Comment by jamespacileo** [comment]
> The unit tests are failing 

was fixed erlier

**Review by Santino-Trade — APPROVED** [review]

**Pull request merged**
